apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - image: mamadly/udacity-cloud-dev:feed-v1
        name: backend-feed
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: JWT_SECRET
          valueFrom: 
            configMapKeyRef:
              name: env-config
              key: JWT_SECRET
        - name: POSTGRESS_USERNAME
          valueFrom: 
            configMapKeyRef:
              name: env-config
              key: POSTGRESS_USERNAME
        - name: POSTGRESS_PASSWORD
          valueFrom: 
            configMapKeyRef:
              name: env-config
              key: POSTGRESS_PASSWORD
        - name: POSTGRESS_DB
          valueFrom: 
            configMapKeyRef:
              name: env-config
              key: POSTGRESS_DB
        - name: POSTGRESS_HOST
          valueFrom: 
            configMapKeyRef:
              name: env-config
              key: POSTGRESS_HOST
        - name: AWS_MEDIA_BUCKET
          valueFrom: 
            configMapKeyRef:
              name: env-config
              key: AWS_MEDIA_BUCKET
        - name: AWS_PROFILE
          valueFrom: 
            configMapKeyRef:
              name: env-config
              key: AWS_PROFILE
        - name: AWS_PROFILE
          valueFrom: 
            configMapKeyRef:
              name: env-config
              key: AWS_PROFILE
      restartPolicy: Always
