apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend 
        version: frontend-v3
    spec:
      containers:
<<<<<<< HEAD
      - image: mamadly/udacity-cloud-dev-frontend:frontend-v3
=======
      - image: mamadly/udacity-cloud-dev-frontend:frontend-v2
>>>>>>> 6c7fef9b0ee37d6c9887e7e55db5ab0e9b80ca30
        name: frontend
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      restartPolicy: Always
     
