version: '2.0'
services:
  backend-feed:
    image: mamadly/udacity-cloud-dev-feed:feed-v1
    volumes:
    - $HOME/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: $POSTGRESS_USERNAME
      POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD
      POSTGRESS_DB: $POSTGRESS_DB
      POSTGRESS_HOST: $POSTGRESS_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_MEDIA_BUCKET: $AWS_MEDIA_BUCKET
      JWT_SECRET: $JWT_SECRET
  backend-user:
    image: mamadly/udacity-cloud-dev-user:user-v1
    environment:
      POSTGRESS_USERNAME: $POSTGRESS_USERNAME
      POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD
      POSTGRESS_DB: $POSTGRESS_DB
      POSTGRESS_HOST: $POSTGRESS_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_MEDIA_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
  frontend:
    image: mamadly/udacity-cloud-dev-frontend:frontend-v1
    ports:
      - "8100:8100"
  reverseproxy:
    image: mamadly/udacity-cloud-dev-reverse-proxy:reverse-proxy-v1
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - backend-user
      - backend-feed
  
