apiVersion: v1
kind: ConfigMap
data:
    POSTGRESS_USERNAME: $POSTGRESS_USERNAME
    POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD
    POSTGRESS_DB: $POSTGRESS_DB
    POSTGRESS_HOST: $POSTGRESS_HOST
    AWS_REGION: $AWS_REGION
    AWS_PROFILE: $AWS_PROFILE
    AWS_MEDIA_BUCKET: $AWS_BUCKET
    JWT_SECRET: $JWT_SECRET
metadata:
  name: env-config