service:
  name: offline-serverless-demo
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

  serverless-offline:
    port:
      3003
  
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
  
  tableNames:
    animals: animals-dev
  
  bucketName:
    animalImages: cat-images

  dynamodb:
    start:
      migrate: true
    stages:
      - dev

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    ANIMALS_TABLE: ${self:custom.tableNames.animals}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  
  animals:
    handler: handler/handler.animals
    events:
      - http:
          method: get
          path: /animals
          cors: true

resources:
  -${file(resources/animals-table.yaml)}
